spring:
  application:
    name: racing-service
  datasource:
    url: jdbc:h2:file:~/racings;AUTO_SERVER=true
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  hibernate:
    ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

# Possible values for these keys are `default`, `xstream`, `java`, and `jackson`.
axon:
  serializer:
    general: jackson
    events: jackson
    messages: xstream